### ISSUE TITLE
LDAP auth fails in OpenShift: Unwilling to perform: too many failed logins.

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#63] opened 2017-08-02 13:26 UTC
In a fresh, successfully finished deployment I cannot login as an IdM user. It yields "Internal error occurred: unexpected response: 500". In the system logs I can see: "logging error output: "Error: LDAP Result Code 53 Unwilling To Perform: Too many failed logins.".
This behavior is not consistently reproducible but appears every 10-20 deployments. Thoughts?

**Comment by thoraxe** [comment] 2017-08-02 13:47
No idea to be honest. Does it happen for 100% of users, or only for a particular user?

**Comment by dmesser** [comment] 2017-08-02 13:59
Only tried with fancyuser1 so far.

**Comment by kmurudi** [comment] 2017-08-02 14:09
I have also faced this issue 1/2 times overall, I just tried a new deployment that time @dmesser

**Comment by dmesser** [comment] 2017-08-06 20:46
Update: it fails intermittently during the lab. At some point oc login with this user fails, then it works again.

**Comment by dmesser** [comment] 2017-08-09 10:07
I am still hitting this, despite updated AMIs.

**Comment by dmesser** [comment] 2017-08-09 13:34
With the new AMIs I am now getting this consistently:

```
TASK [login as fancyuser1] *****************************************************************************************************************************************
Wednesday 09 August 2017  13:33:11 +0000 (0:00:00.031)       0:14:48.662 ******
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": "oc login -u 'fancyuser1' -p 'openshift'",
    "delta": "0:00:00.226301",
    "end": "2017-08-09 13:33:11.893101",
    "failed": true,
    "rc": 1,
    "start": "2017-08-09 13:33:11.666800"
}

STDOUT:

Login failed (401 Unauthorized)
```

@cooktheryan @thoraxe ^^

**Comment by cooktheryan** [comment] 2017-08-09 13:38
@dmesser are you using master branch?

**Comment by dmesser** [comment] 2017-08-09 13:40
Using my branch which is currently in sync with master.

**Comment by cooktheryan** [comment] 2017-08-09 13:45
k im going to deploy master now. Can you let me know what playbook you ran to get that

**Comment by cooktheryan** [comment] 2017-08-09 14:15
the problem is that groupsync.yaml is not getting the correct values.

```
kind: LDAPSyncConfig
apiVersion: v1
url: ldap://idm.unset.ocp-admin.aws.openshifttestdrive.com
ca: /etc/origin/master/ipa-ca.crt
bindDN: uid=admin,cn=users,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
bindPassword: ldapadmin
rfc2307:
  groupsQuery:
    baseDN: cn=groups,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
    derefAliases: never
    filter: '(|(cn=ose-*))'
  groupUIDAttribute: dn
  groupNameAttributes:
  - cn
  groupMembershipAttributes:
  - member
  usersQuery:
    baseDN: cn=users,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
    derefAliases: never
  userUIDAttribute: dn
  userNameAttributes:
  - uid

```

PR in route

**Comment by kmurudi** [comment] 2017-08-09 14:16
But it was getting the values when I tried for my environment yesterday

On Aug 9, 2017 10:15 AM, "Ryan Cook" <notifications@github.com> wrote:

the problem is that groupsync.yaml is not getting the correct values.

kind: LDAPSyncConfig
apiVersion: v1
url: ldap://idm.unset.ocp-admin.aws.openshifttestdrive.com
ca: /etc/origin/master/ipa-ca.crt
bindDN: uid=admin,cn=users,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
bindPassword: ldapadmin
rfc2307:
  groupsQuery:
    baseDN: cn=groups,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
    derefAliases: never
    filter: '(|(cn=ose-*))'
  groupUIDAttribute: dn
  groupNameAttributes:
  - cn
  groupMembershipAttributes:
  - member
  usersQuery:
    baseDN: cn=users,cn=accounts,dc=unset,dc=ocp-admin,dc=aws,dc=openshifttestdrive,dc=com
    derefAliases: never
  userUIDAttribute: dn
  userNameAttributes:
  - uid


PR in route

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-cns-testdrive/issues/63#issuecomment-321268255>,
or mute the thread

**Comment by dmesser** [comment] 2017-08-09 14:22
@cooktheryan I am running this:

ansible-playbook /opt/lab/code/tests/{installation_automation.yml,installation_verify.yml,cns-deploy_automation.yml,cns-deploy_verify.yml,cns-management_automation.yml,cns-management_verify.yml}

it fails in the cns-management_automation.yml playbook when we log on as a user to create project that leverages PVC from CNS.

**Comment by cooktheryan** [comment] 2017-08-09 14:26
K I just pushed something. Will update soon

**Comment by cooktheryan** [comment] 2017-08-09 15:14
It looks like the bug is the master-config.yaml still trying to track it
down

**Comment by thoraxe** [comment] 2017-08-18 19:40
@cooktheryan so can we close this based on #109 ?

**Comment by cooktheryan** [comment] 2017-08-18 19:50
yep closing

**Closed by cooktheryan** 2017-08-18 19:50 UTC
